### ISSUE TITLE
Unhandled exception executing command 'twar' in plugin TownyWars v1.3.0-pre-1

### ISSUE THREAD

**Issue by kenny1998cr** [karlovm/TownyWars#2]
When I type the command /twars n this error is display.
![Error 2](https://user-images.githubusercontent.com/32584296/89676866-9e972680-d8a9-11ea-9de1-8758208b23d8.png)

This is the error message on the console

![Error](https://user-images.githubusercontent.com/32584296/89676892-aa82e880-d8a9-11ea-99f3-2c71f34d34b5.png)

Spigot version: 1.16.1
Towny Wars version: 1.3.0

Full console message:

[ERROR] null

org.bukkit.command.CommandException: Unhandled exception executing command 'twar' in plugin TownyWars v1.3.0-pre-1

at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]

at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]

at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:757) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]

at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1703) [spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]

at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1546) [spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]

at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) [spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]

at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]

at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) [spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]

at net.minecraft.server.v1_16_R1.PlayerConnectionUtils$$Lambda$4310/0000000078098C50.run(Unknown Source) [spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]

at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) [spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]

at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]

at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]

at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]

at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:943) [spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]

at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:936) [spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]

at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]

at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:920) [spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]

at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:852) [spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]

at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) [spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]

at net.minecraft.server.v1_16_R1.MinecraftServer$$Lambda$2926/00000000418345C0.run(Unknown Source) [spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]

at java.lang.Thread.run(Thread.java:823) [?:1.8.0_265]

Caused by: java.lang.NoSuchMethodError: com/palmergames/bukkit/towny/object/Town.getAccount()Lcom/palmergames/bukkit/towny/object/economy/BankAccount; (loaded from file:/home/gs-41383/plugins/Towny-0.96.2.0.jar by org.bukkit.plugin.java.PluginClassLoader@c02652b5) called from class com.etysoft.townywars.Commands (loaded from file:/home/gs-41383/plugins/TownyWars.jar by org.bukkit.plugin.java.PluginClassLoader@24e9f626).

at com.etysoft.townywars.Commands.onCommand(Commands.java:384) ~[?:?]

at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]

... 20 more

**Comment by karlovm** [comment]
Your Towny version is outdated. See the version compatibility table.
